var stimuli =[
    {"stimulus":"../utils/circle.png", "label":"You", "data": {"screen": "trial", "shape": "circle", "label_cond": "You"}},
    {"stimulus":"../utils/circle.png", "label":"Friend", "data": {"screen": "trial", "shape": "circle", "label_cond": "Friend"}},
    {"stimulus":"../utils/circle.png", "label":"Stranger", "data": {"screen": "trial", "shape": "circle", "label_cond": "Stranger"}},
    {"stimulus":"../utils/triangle.png", "label":"You", "data": {"screen": "trial", "shape": "triangle", "label_cond": "You"}},
    {"stimulus":"../utils/triangle.png", "label":"Friend", "data": {"screen": "trial",  "shape": "triangle", "label_cond": "Friend"}},
    {"stimulus":"../utils/triangle.png", "label":"Stranger", "data": {"screen": "trial", "shape": "triangle", "label_cond": "Stranger"}},
    {"stimulus":"../utils/square.png", "label":"You", "data": {"screen": "trial", "shape": "square", "label_cond": "You"}},
    {"stimulus":"../utils/square.png", "label":"Friend", "data": {"screen": "trial", "shape": "square", "label_cond": "Friend"}},
    {"stimulus":"../utils/square.png", "label":"Stranger", "data": {"screen": "trial", "shape": "square", "label_cond": "Stranger"}},
]

var stimuli_training = [
    {"stimulus":"../utils/circle.png", "label1":"You", "label2":"Friend", "label3":"Stranger", "data": {"screen": "practice_trial", "shape": "circle", "label_cond":"YFS"}},
    {"stimulus":"../utils/circle.png", "label1":"You", "label2":"Friend", "label3":"Stranger", "data": {"screen": "practice_trial", "shape": "circle", "label_cond": "YFS"}},
    {"stimulus":"../utils/circle.png", "label1":"You", "label2":"Friend", "label3":"Stranger", "data": {"screen": "practice_trial", "shape": "circle", "label_cond": "YFS"}},
    {"stimulus":"../utils/triangle.png", "label1":"You", "label2":"Friend", "label3":"Stranger",  "data": {"screen": "practice_trial", "shape": "triangle", "label_cond": "YFS"}},
    {"stimulus":"../utils/triangle.png", "label1":"You", "label2":"Friend", "label3":"Stranger", "data": {"screen": "practice_trial",  "shape": "triangle", "label_cond": "YFS"}},
    {"stimulus":"../utils/triangle.png", "label1":"You", "label2":"Friend", "label3":"Stranger", "data": {"screen": "practice_trial", "shape": "triangle", "label_cond": "YFS"}},
    {"stimulus":"../utils/square.png", "label1":"You", "label2":"Friend", "label3":"Stranger", "data": {"screen": "practice_trial", "shape": "square", "label_cond": "YFS"}},
    {"stimulus":"../utils/square.png", "label1":"You", "label2":"Friend", "label3":"Stranger",  "data": {"screen": "practice_trial", "shape": "square", "label_cond": "YFS"}},
    {"stimulus":"../utils/square.png", "label1":"You", "label2":"Friend", "label3":"Stranger",  "data": {"screen": "practice_trial", "shape": "square", "label_cond": "YFS"}},
    {"stimulus":"../utils/circle.png", "label1":"You", "label2":"Stranger", "label3":"Friend","data": {"screen": "practice_trial", "shape": "circle", "label_cond": "YSF"}},
    {"stimulus":"../utils/circle.png", "label1":"You", "label2":"Stranger", "label3":"Friend", "data": {"screen": "practice_trial", "shape": "circle", "label_cond": "YSF"}},
    {"stimulus":"../utils/circle.png", "label1":"You", "label2":"Stranger", "label3":"Friend","data": {"screen": "practice_trial", "shape": "circle", "label_cond": "YSF"}},
    {"stimulus":"../utils/triangle.png", "label1":"You", "label2":"Stranger", "label3":"Friend","data": {"screen": "practice_trial", "shape": "triangle", "label_cond": "YSF"}},
    {"stimulus":"../utils/triangle.png", "label1":"You", "label2":"Stranger", "label3":"Friend","data": {"screen": "practice_trial",  "shape": "triangle", "label_cond": "YSF"}},
    {"stimulus":"../utils/triangle.png", "label1":"You", "label2":"Stranger", "label3":"Friend","data": {"screen": "practice_trial", "shape": "triangle", "label_cond": "YSF"}},
    {"stimulus":"../utils/square.png", "label1":"You", "label2":"Stranger", "label3":"Friend","data": {"screen": "practice_trial", "shape": "square", "label_cond": "YSF"}},
    {"stimulus":"../utils/square.png", "label1":"You", "label2":"Stranger", "label3":"Friend","data": {"screen": "practice_trial", "shape": "square", "label_cond": "YSF"}},
    {"stimulus":"../utils/square.png", "label1":"You", "label2":"Stranger", "label3":"Friend","data": {"screen": "practice_trial", "shape": "square", "label_cond": "YSF"}},
    {"stimulus":"../utils/circle.png", "label1":"Stranger", "label2":"Friend", "label3":"You","data": {"screen": "practice_trial", "shape": "circle", "label_cond": "SFY"}},
    {"stimulus":"../utils/circle.png", "label1":"Stranger", "label2":"Friend", "label3":"You", "data": {"screen": "practice_trial", "shape": "circle", "label_cond": "SFY"}},
    {"stimulus":"../utils/circle.png", "label1":"Stranger", "label2":"Friend", "label3":"You","data": {"screen": "practice_trial", "shape": "circle", "label_cond": "SFY"}},
    {"stimulus":"../utils/triangle.png", "label1":"Stranger", "label2":"Friend", "label3":"You","data": {"screen": "practice_trial", "shape": "triangle", "label_cond": "SFY"}},
    {"stimulus":"../utils/triangle.png", "label1":"Stranger", "label2":"Friend", "label3":"You","data": {"screen": "practice_trial",  "shape": "triangle", "label_cond": "SFY"}},
    {"stimulus":"../utils/triangle.png", "label1":"Stranger", "label2":"Friend", "label3":"You","data": {"screen": "practice_trial", "shape": "triangle", "label_cond": "SFY"}},
    {"stimulus":"../utils/square.png", "label1":"Stranger", "label2":"Friend", "label3":"You","data": {"screen": "practice_trial", "shape": "square", "label_cond": "SFY"}},
    {"stimulus":"../utils/square.png", "label1":"Stranger", "label2":"Friend", "label3":"You","data": {"screen": "practice_trial", "shape": "square", "label_cond": "SFY"}},
    {"stimulus":"../utils/square.png", "label1":"Stranger", "label2":"Friend", "label3":"You","data": {"screen": "practice_trial", "shape": "square", "label_cond": "SFY"}},
    {"stimulus":"../utils/circle.png", "label1":"Stranger", "label2":"You", "label3":"Friend","data": {"screen": "practice_trial", "shape": "circle", "label_cond": "SYF"}},
    {"stimulus":"../utils/circle.png", "label1":"Stranger", "label2":"You", "label3":"Friend", "data": {"screen": "practice_trial", "shape": "circle", "label_cond": "SYF"}},
    {"stimulus":"../utils/circle.png", "label1":"Stranger", "label2":"You", "label3":"Friend","data": {"screen": "practice_trial", "shape": "circle", "label_cond": "SYF"}},
    {"stimulus":"../utils/triangle.png", "label1":"Stranger", "label2":"You", "label3":"Friend","data": {"screen": "practice_trial", "shape": "triangle", "label_cond": "SYF"}},
    {"stimulus":"../utils/triangle.png", "label1":"Stranger", "label2":"You", "label3":"Friend","data": {"screen": "practice_trial",  "shape": "triangle", "label_cond": "SYF"}},
    {"stimulus":"../utils/triangle.png", "label1":"Stranger", "label2":"You", "label3":"Friend","data": {"screen": "practice_trial", "shape": "triangle", "label_cond": "SYF"}},
    {"stimulus":"../utils/square.png", "label1":"Stranger", "label2":"You", "label3":"Friend","data": {"screen": "practice_trial", "shape": "square", "label_cond": "SYF"}},
    {"stimulus":"../utils/square.png", "label1":"Stranger", "label2":"You", "label3":"Friend","data": {"screen": "practice_trial", "shape": "square", "label_cond": "SYF"}},
    {"stimulus":"../utils/square.png", "label1":"Stranger", "label2":"You", "label3":"Friend","data": {"screen": "practice_trial", "shape": "square", "label_cond": "SYF"}},
    {"stimulus":"../utils/circle.png", "label1":"Friend", "label2":"You", "label3":"Stranger", "data": {"screen": "practice_trial", "shape": "circle", "label_cond":"FYS"}},
    {"stimulus":"../utils/circle.png", "label1":"Friend", "label2":"You", "label3":"Stranger", "data": {"screen": "practice_trial", "shape": "circle", "label_cond": "FYS"}},
    {"stimulus":"../utils/circle.png", "label1":"Friend", "label2":"You", "label3":"Stranger", "data": {"screen": "practice_trial", "shape": "circle", "label_cond": "FYS"}},
    {"stimulus":"../utils/triangle.png", "label1":"Friend", "label2":"You", "label3":"Stranger",  "data": {"screen": "practice_trial", "shape": "triangle", "label_cond": "FYS"}},
    {"stimulus":"../utils/triangle.png", "label1":"Friend", "label2":"You", "label3":"Stranger", "data": {"screen": "practice_trial",  "shape": "triangle", "label_cond": "FYS"}},
    {"stimulus":"../utils/triangle.png", "label1":"Friend", "label2":"You", "label3":"Stranger", "data": {"screen": "practice_trial", "shape": "triangle", "label_cond": "FYS"}},
    {"stimulus":"../utils/square.png", "label1":"Friend", "label2":"You", "label3":"Stranger", "data": {"screen": "practice_trial", "shape": "square", "label_cond": "FYS"}},
    {"stimulus":"../utils/square.png", "label1":"Friend", "label2":"You", "label3":"Stranger",  "data": {"screen": "practice_trial", "shape": "square", "label_cond": "FYS"}},
    {"stimulus":"../utils/square.png", "label1":"Friend", "label2":"You", "label3":"Stranger",  "data": {"screen": "practice_trial", "shape": "square", "label_cond": "FYS"}},
    {"stimulus":"../utils/circle.png", "label1":"Friend", "label2":"Stranger", "label3":"You", "data": {"screen": "practice_trial", "shape": "circle", "label_cond":"FSY"}},
    {"stimulus":"../utils/circle.png", "label1":"Friend", "label2":"Stranger", "label3":"You", "data": {"screen": "practice_trial", "shape": "circle", "label_cond": "FSY"}},
    {"stimulus":"../utils/circle.png", "label1":"Friend", "label2":"Stranger", "label3":"You", "data": {"screen": "practice_trial", "shape": "circle", "label_cond": "FSY"}},
    {"stimulus":"../utils/triangle.png", "label1":"Friend", "label2":"Stranger", "label3":"You",  "data": {"screen": "practice_trial", "shape": "triangle", "label_cond": "FSY"}},
    {"stimulus":"../utils/triangle.png", "label1":"Friend", "label2":"Stranger", "label3":"You", "data": {"screen": "practice_trial",  "shape": "triangle", "label_cond": "FSY"}},
    {"stimulus":"../utils/triangle.png", "label1":"Friend", "label2":"Stranger", "label3":"You", "data": {"screen": "practice_trial", "shape": "triangle", "label_cond": "FSY"}},
    {"stimulus":"../utils/square.png", "label1":"Friend", "label2":"Stranger", "label3":"You", "data": {"screen": "practice_trial", "shape": "square", "label_cond": "FSY"}},
    {"stimulus":"../utils/square.png", "label1":"Friend", "label2":"Stranger", "label3":"You",  "data": {"screen": "practice_trial", "shape": "square", "label_cond": "FSY"}},
    {"stimulus":"../utils/square.png", "label1":"Friend", "label2":"Stranger", "label3":"You",  "data": {"screen": "practice_trial", "shape": "square", "label_cond": "FSY"}},
]